def SdgDict():
    sdgDict = {'Adipic Acid': [13,3,12,9], 
        'Afforestation / Reforestation': [6,13,15,9], 
        'Agricultural Land Management': [6,13,2,15], 
        'Agriculture & Forestry': [6,13,2,15], 
        'Agriculture Forestry and Other Land Use': [6,13,2,15], 
        'Agriculture Forestry and Other Land Use; Energy industries (renewable/non-renewable sources)': [6,13,2,15], 
        'Agriculture Forestry and Other Land Use; Energy industries (renewable/non-renewable sources); Livestock, enteric fermentation, and manure management; Transport; Waste handling and disposal': [6,13,2,15], 
        'Agriculture Forestry and Other Land Use; Energy industries (renewable/non-renewable sources); Waste handling and disposal': [6,13,2,15], 
        'Agriculture Forestry and Other Land Use; Livestock, enteric fermentation, and manure management': [6,13,2,15], 
        'Agriculture Forestry and Other Land Use; Waste handling and disposal': [6,13,2,15], 
        'Agriculture land management': [6,13,2,15], 
        'Avoided Conversion': [6,13,15,9], 
        'Avoided Conversion - ARB Compliance': [6,13,15,9], 
        'Avoided Grassland Conversion': [6,13,15,9], 
        'Canada Grassland': [6,13,15,9], 
        'Carbon Capture & Storage (CCS)': [13,9,3,12], 
        'Chemical industry': [9,8,13,12], 
        'Chemical industry; Energy demand; Energy industries (renewable/non-renewable sources)': [9,8,13,12], 
        'Chemical industry; Energy industries (renewable/non-renewable sources)': [9,8,13,12], 
        'Chemical industry; Transport': [9,8,13,12], 
        'Clearfell only': [6,13,2,15], 
        'Coal Mine Methane': [9,13,3,8], 
        'Coal Mine Methane - Drainage': [9,13,3,8], 
        'Coal Mine Methane - VAM': [9,13,3,8], 
        'Conservation-Based Forest Management': [6,13,15,9], 
        'Construction': [11,9,8,13], 
        'Construction; Energy industries (renewable/non-renewable sources)': [11,9,8,13], 
        'Construction; Manufacturing industries': [11,9,8,13], 
        'Continuous cover system': [6,13,15,9], 
        'Energy demand': [7,8,9,11], 
        'Energy demand; Energy distribution; Energy industries (renewable/non-renewable sources)': [7,8,9,11], 
        'Energy demand; Energy industries (renewable/non-renewable sources)': [7,8,9,11], 
        'Energy demand; Energy industries (renewable/non-renewable sources); Waste handling and disposal': [7,8,9,11], 
        'Energy demand; Waste handling and disposal': [7,8,9,11], 
        'Energy distribution': [7,8,9,11], 
        'Energy distribution; Energy industries (renewable/non-renewable sources); Transport': [7,8,9,11], 
        'Energy distribution; Transport': [7,8,9,11], 
        'Energy Efficiency': [7,9,11,8], 
        'Energy industries (renewable/non-renewable sources)': [7,9,11,8], 
        'Energy industries (renewable/non-renewable sources); Fugitive emissions from fuels (solid, oil and gas)': [7,9,11,8], 
        'Energy industries (renewable/non-renewable sources); Fugitive emissions from fuels (solid, oil and gas); Mining/mineral production': [7,9,11,8], 
        'Energy industries (renewable/non-renewable sources); Livestock, enteric fermentation, and manure management': [7,9,11,8], 
        'Energy industries (renewable/non-renewable sources); Livestock, enteric fermentation, and manure management; Transport': [7,9,11,8], 
        'Energy industries (renewable/non-renewable sources); Livestock, enteric fermentation, and manure management; Waste handling and disposal': [7,9,11,8], 
        'Energy industries (renewable/non-renewable sources); Manufacturing industries': [7,9,11,8], 
        'Energy industries (renewable/non-renewable sources); Mining/mineral production': [7,9,11,8], 
        'Energy industries (renewable/non-renewable sources); Transport': [7,9,11,8], 
        'Energy industries (renewable/non-renewable sources); Waste handling and disposal': [7,9,11,8], 
        'Forest': [6,13,15,9], 
        'Forest Carbon': [6,13,15,9], 
        'Forest Conservation & Avoided Deforestation': [6,13,15,9], 
        'Forest Restoration': [6,13,15,9], 
        'Forestry - MX': [3,13,8,1], 
        'Fuel Switching': [7,9,13,12], 
        'Fugitive emissions from fuels (solid, oil and gas)': [13,3,12,9], 
        'Fugitive emissions from fuels (solid, oil and gas); Mining/mineral production': [13,3,12,9], 
        'Fugitive emissions from production and consumption of halocarbons and sulphur hexafluoride': [13,3,12,9], 
        'Fugitive emissions from production and consumption of halocarbons and sulphur hexafluoride; Manufacturing industries': [13,3,12,9], 
        'Improved Forest Management': [6,13,15,9],
        'Improved forest management': [6,13,15,9],
        'Improved Forest Management - ARB Compliance': [6,13,15,9], 
        'Industrial Gas Substitution': [9,13,12,3], 
        'Industrial Process Emissions': [9,13,12,3], 
        'Landfill - MX': [9,11,13,12], 
        'Landfill Gas Capture & Combustion': [9,11,13,12], 
        'Landfill Gas Capture/Combustion': [9,11,13,12], 
        'Livestock - ARB Compliance': [9,11,13,12], 
        'Livestock - MX': [9,11,13,12], 
        'Livestock Gas Capture/Combustion': [9,11,13,12], 
        'Livestock Waste Management': [9,13,2,11], 
        'Livestock, enteric fermentation, and manure management': [9,11,13,12], 
        'Livestock, enteric fermentation, and manure management; Waste handling and disposal': [9,11,13,12], 
        'Low Carbon Cement': [13,9,11,8], 
        'Manufacturing industries': [13,9,11,8], 
        'Manufacturing industries; Waste handling and disposal': [13,9,11,8], 
        'Metal production': [13,9,11,8], 
        'Metal production; Mining/mineral production': [13,9,11,8], 
        'Mine Methane Capture - ARB Compliance': [13,9,3,12], 
        'Mining/mineral production': [13,9,11,8], 
        'Mixed mainly clearfell': [6,13,15,9], 
        'Mixed mainly continuous cover system': [6,13,15,9], 
        'Mixed mainly no thin or clearfell': [6,13,15,9], 
        'Mixed mainly thin and clearfell': [6,13,15,9], 
        'Mixed mainly thinning': [6,13,15,9], 
        'Nitric Acid N2O- Secondary Catalyst': [9,12,13,3], 
        'Nitric Acid N2O- Tertiary Catalyst': [9,12,13,3], 
        'Nitrogen Management': [9,12,13,3], 
        'No thinning or clearfell': [6,13,15,9], 
        'Organic Waste Composting': [1,2,3,13], 
        'Organic Waste Digestion': [1,2,3,13], 
        'Ozone Depleting Substances': [9,12,13,3], 
        'Ozone Depleting Substances - Article 5 Imports': [9,12,13,3], 
        'Ozone Depleting Substances - U.S.': [9,12,13,3], 
        'Ozone Depleting Substances - U.S. - ARB Compliance': [9,12,13,3], 
        'Ozone Depleting Substances ñ MX': [9,12,13,3], 
        'Peatland Restoration': [6,13,15,14], 
        'Phosphorus': [9,12,13,3], 
        'REDD': [6,13,15,9], 
        'Reduced emissions from deforestation & degradation': [6,13,15,9], 
        'Reforestation': [6,13,15,9], 
        'Reforestation - ARB Compliance': [6,13,15,9], 
        'Renewable Energy': [7,11,13,9], 
        'Sequestration': [6,13,15,9], 
        'Soil Enrichment': [2,3,4,5], 
        'Temperature': [13,3,11,3], 
        'Thin and clearfell': [6,13,15,9], 
        'Thin only': [6,13,15,9], 
        'Transport': [9,11,13,3], 
        'Transport / Fleet Efficiency': [9,11,13,3], 
        'Transport; Waste handling and disposal': [9,11,13,3], 
        'W+ Education & Knowledge': [5,9,10,8], 
        'W+ Income & Assets': [5,9,10,8], 
        'W+ Time': [5,9,10,8], 
        'Waste handling and disposal': [9,11,13,12], 
        'Wastewater Treatment': [9,11,13,12], 
        'Water Flow Restoration': [3,6,9,13], 
        'Wetland Restoration': [3,6,9,13]
    }
    return sdgDict


#testing
if __name__ == "__main__":
    sdgDict = SdgDict()
    for key, value in sdgDict.items():
        print(f"{key}: {value}")
